### ISSUE TITLE
Remove node_modules bin path from Makefile

### ISSUE THREAD

**Issue by MichaelCurrin** [chilllab/react-nice-avatar#12]
Just an idea to make your Makefile lighter to follow.

If you use `npx`, then you can execute files in node_modules/bin directly.

e.g.

```sh
$ npm i eslint

$ npx eslint --fix
```

So Makefile can be like this, without setting up the bin path.

```mk
lint:
  npx eslint --fix
```

**Comment by MichaelCurrin** [comment]
Oh and if `eslint` is _not_ installed in the project, then it will be referenced globally, or it will be downloaded and run globally.

**Comment by MichaelCurrin** [comment]
Another option is to use `scripts` in package.json which is empty.

```json
{
  "scripts": {
    "lint": "eslint --fix"
  }
}
```

Then you can run

```sh
$ npm run lint
```

Without caring about bin path or `npx`.

**Comment by wwayne** [comment]
Thanks for your reminder of the best practice, I know all of these, just didn't pay attention, I will take a try of npx next time
