### ISSUE TITLE
Avatar download image size larger than avatar size

### ISSUE THREAD

**Issue by with-heart** [chilllab/react-nice-avatar#4]
Downloaded avatar images are 361x445 rather than matching what appears to be 350x350 for the avatars.

Example download:

<kbd>

![avatar (1)](https://user-images.githubusercontent.com/1954752/120525494-2b195500-c3a6-11eb-9b00-ad81434be18d.png)

</kbd>

**Comment by wwayne** [comment]
Thanks, issue fixed for the demo
