### ISSUE TITLE
Remove unnecessary ignored items

### ISSUE THREAD

**Issue by MichaelCurrin** [chilllab/react-nice-avatar#8]
These rows should all be removed from .gitignore.

```
!.gitignore
!.npmignore
!.eslintignore
!.travis.yml
!.babelrc
!.eslintrc
```

Using ! means _don't ignore_, but if those are not ignored with a prior rule then there is no point to list them.

**Comment by wwayne** [comment]
Yes seems no need, I got used to listing `.*` files explicitly in the ignore files, thanks for the reminding
