### ISSUE TITLE
Remove phony lines from Makefile

### ISSUE THREAD

**Issue by MichaelCurrin** [chilllab/react-nice-avatar#9]
you have no overlap between directory names and make commands, so you don't need phony. It doesn't do anything here. Like  this 
```
.PHONY lint
```

Only matters if you had an actual directory named lint, whether ignored or not

The phony lines help if you actually had a directory called `build` and if you ran `make build` you would get unexpected reused because make would look at the directory, which is independent of the make command.

**Comment by wwayne** [comment]
Thank you, I list the command there in case I forgot them and I create a folder with the same name later, maybe not a best practice, more personal preference

**Comment by MichaelCurrin** [comment]
I have seen others with that style as well of ignoring everything.

I prefer less code to manage - remove code that doesn't actually do anything yet has to maintained (if you renamed `lint` command you'd _also_ have to update .PHONY to be consistent and if you added another command you'd have to duplicate its name in a .PHONY too).
 
Also note that it is tolerable to omit the .PHONY bit.

If for example you use `build` instead of `dist` for output.
If you ran

```
make build
```
Then _make_ will tell you something useful so you know you need to add the .PHONY next.

e.g. I tried this in a random project with `build` directory in it and not even with a Makefile.

```
make: Nothing to be done for `build'.
```
